apiVersion: v1
kind: Service
metadata:
  name: catalog-service-02
  labels:
    app: catalog-service-02
spec:
  type: ClusterIP
  selector:
    app: catalog-service-02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001